### ISSUE TITLE
LAN won’t work

### ISSUE THREAD

**Issue by Tats2252** [katubug/CottageWitch119#100]
**What Cottage Witch version are you using?**
Version: 1.16.19

**How much RAM you have allocated (recommended 6-8gb)**
You can check this by viewing your launcher's settings. If you do not have 6gb allocated, please try this first. 8gb

**Clearly describe the issue**

We’re trying to play on a LAN world together but the world is not being listed even though we’ve checked our firewalls and are on the same network and mod pack version. When we try to connect directly via ip address the connection times out.

**Screenshots**
Attach relevant screenshots here.

**Comment by katubug** [comment]
I'm afraid the modpack doesn't do anything to LAN connections, I'm not sure why this is occuring.

**Comment by Tats2252** [comment]
Thank you for clarifying! We’re trying to set it up on our current Biscet server. Is there a way to load 1.16.19 instead of the most recent? Oh the biomes you’ll go makes it for me :). Thank you!

**Comment by katubug** [comment]
The most recent version should still contain BYG, but also you should be
able to choose which version to install on your server! I don't know how it
works with bisect, but with Akliz when you install the modpack, you choose
the version from a drop-down menu. Bisect might have something similar,
otherwise you might need to contact their support. I hope this helps!
