### ISSUE TITLE
Issues connecting to private server (that I manage)

### ISSUE THREAD

**Issue by ThirdEyeRose** [katubug/CottageWitch119#14]
👋🏻 Hiya - don't know if I'm in the right place, but I figured I might as well try here.

I'm setting up my own server using the server installation files provided by CurseForge. I got everything installed and I can connect to the server from multiple machines. However, clients when connecting fall endlessly in the void for a while before the world loads and then are presented with a "waiting for server..." error when trying to interact.

I can provide error messages from both the server and the client, but there's _a lot_ and I'm not sure what's important vs what's noise. A majority of messages I'm getting when the connection times out for a client is:

```
[19:30:08] [Netty Epoll Server IO #2/WARN] [co.co.Connectivity/]: io.netty.channel.StacklessClosedChannelException
```

Is this something that you can assist with? If so, what additional information I can provide?

**Comment by katubug** [comment]
Hi! So the Stackless error is due to Connectivity mod. It's been reported
but no solution yet. The only workaround is to try reconnecting, and you
might need to restart your server.

Beyond that, it sounds like the server is struggling to provide clients
with the terrain. It's normal to fall a bit before terrain loads, but if
you're getting "waiting for server" then you either have some entity or
something in the loaded chunks which is stalling out the server, or you
might need to allocate more RAM.

Can you tell me how much RAM the server has allocated, and what happens if
you try a newly generated world (you can just rename the world folder and a
new one will generate)?

**Comment by ThirdEyeRose** [comment]
Thank you for the quick reply! Much appreciated!

I just noticed that you had an update on the mod that I don't think I have yet, so I'm going to try the latest updates and see if the connection issues persist. Then I'll be back with an update.

As for the resources given to the server, I'm running a Digital Ocean droplet with 8GB RAM and a 60GB Disk and 4vCPUs.

**Comment by ThirdEyeRose** [comment]
Updating the server and client to 1.12.2a does not seem to have changed the issue.

**Comment by katubug** [comment]
Hmm. It seems like you should be fine, hardware-wise. Did you test whether
a new world would fix the issue?

**Comment by ThirdEyeRose** [comment]
I did. I did a completely fresh install with a new world but the behavior was pretty much the same.

**Comment by katubug** [comment]
I gotta admit, I'm stumped. If it was me, I'd ask the server-admin channel
over at the moddedmc discord: https://discord.gg/moddedmc/

They're much better than I am at sysadmin stuff.

**Comment by ThirdEyeRose** [comment]
Will do, thanks so much!

**Comment by katubug** [comment]
Best of luck!

**Comment by katubug** [comment]
Were they able to help? Should I close this issue?
