### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by GiGDDragon** [katubug/CottageWitch119#17]
**What Cottage Witch version are you using?**
Version: 1.12.2a

**What were you doing when you crashed?**
Had killed a wandering wine trader, captured his mules, and tamed them. then because I had a breeding tarot card on, they got hearts and the instant the breed server crashed. Then recrashed every time I tried to join until a fellow player killed them before I tried joining.

**To Reproduce**
1. Kill wandering wine trader
2. capture and tame his mules
3. use tarot breeding card
4. server crashes

**Crash Reports or Latest.log**
[crash-2023-04-09_19.42.51-server.txt](https://github.com/katubug/CottageWitch119/files/11196005/crash-2023-04-09_19.42.51-server.txt)

**Comment by katubug** [comment]
Hi! Thank you so much for reporting this. It's possible that if you update
to 1.13.0A you will not have any issues, although the mules might be
missing. That update removes the Vinery mod due to another unresolved crash.

If you're up for it, I recommend reporting this to the Vinery issue tracker
here: https://www.curseforge.com/minecraft/mc-mods/lets-do-wine/issues

But it seems like they're not really responding to reports at this time, so
I don't blame you if you don't feel like it.

If updating the modpack doesn't give you access to your world again, my
recommendation would be to load from a recent backup. Otherwise, feel free
to reply and I'll see if I have any ideas.
