### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by ShvdowFall** [katubug/CottageWitch119#23]
**What Cottage Witch version are you using?**
Version: 1.19.2

**What were you doing when you crashed?**
I downloaded an updated version of the modpack, and when I finished I started up the game. Some mods were missing from the modpack when I tried to enter a server so I went ahead and installed them and placed them in from a friend's mod folder so to have the same files. When entering AppleCrates 1.19.2 - 2.7.1, I get Exit Code 1. Any other mod is fine, however when I put apple crates in. My game doesn't load correctly. Friend who I acquired the same Applecrates mod from, is able to boot fine.

**To Reproduce**
1. Go to Curseforge
2. Click on Play Cottage Witch
3. Minecraft Launcher opens and hit play.

**Screenshots**
![Screenshot (16)](https://user-images.githubusercontent.com/130922700/232327863-fedba2bc-6181-4396-a932-c4d44c1a1e68.png)

**Crash Reports or Latest.log**
Drag and drop your latest.log and/or crash report here, or paste a pastebin.com or gist.github.com link with their contents. To find these files (assuming CurseForge launcher), click the 3 dots next to the Play button and choose "Open Folder." Logs are in the /logs/ folder, and crashes are in /crash-reports/. *These files are often CRUCIAL to diagnosing your issue, so please include them.*

EXIT CODE: 1
None of my crash reports go to CurseForge unfortunately because my actual Minecraft Launcher opens and crashes there. If there's a workaround to this, let me know and I'll gladly supply crash reports and logs.

**Additional context**
Considering this issue has only happened with me and not other people who have Apple Crates, it might be a hardware issue on my end, but I wouldn't have a clue as to what it is. My RAM is currently bumped all the way up. 12288 MBs. Before it was lower and was still crashing anyway. Thanks for your time : )

**Comment by katubug** [comment]
Hi, so firstly, you shouldn't need all 12gb allocated. I recommend 10 or less, or you could have lag spikes.

Secondly, it sounds like your modpack version is a different version than the server. Rather than install a missing mod manually, it's best to change the modpack version using whichever manager you use (curseforge or prism launcher or whatever). There are many other changes to each modpack version which are contained elsewhere than the mods folder, so those can cause conflict issues.

I would ask your server owner which version of the modpack (like 1.19.2-1.13.3 or similar) they use so that you can use that version.
