### ISSUE TITLE
green recipe book not appearing

### ISSUE THREAD

**Issue by nicksgam3** [katubug/CottageWitch119#37]
**Describe the bug**
well, im playing LAN and my sister connected but she doesn't have the green book that appears when you open inventory that shows the recipes. i have the book but she doesn't. 

**To Reproduce**
im not sure, i guess host a LAN and have someone join and check if they have the green book.

**Expected behavior**
they shouldn't have the green book.

**Screenshots**

**What Cottage Witch version are you using?**
Version: 1.19.2

**Additional context**
i hosted and when she joined she didn't have the green book. Then she hosted and I didn't have the green book.

**Comment by katubug** [comment]
I'm so sorry I didn't respond to this in a timely fashion. Apparently github just didn't notify me about a ton of things. This was caused by the mod FastSuite, which we have now replaced with RecipeEssentials. I know that's not helpful now, but in case someone finds this via google search, maybe it'll help.

Thank you for reporting.
