### ISSUE TITLE
[Crash] Crash on M1 Mac

### ISSUE THREAD

**Issue by Calciume** [katubug/CottageWitch119#57]
**What Cottage Witch version are you using?**
Version: 1.15.7

**What were you doing when you crashed?**
The game crashes during world gen

**To Reproduce**
1. Load the modpack on an M1 Mac
2. Attempt to make a new world
3. Game crashes once world gen begins

**Screenshots**

**Crash Reports or Latest.log**
Drag and drop your latest.log and/or crash report here, or paste a pastebin.com or gist.github.com link with their contents. To find these files (assuming CurseForge launcher), click the 3 dots next to the Play button and choose "Open Folder." Logs are in the /logs/ folder, and crashes are in /crash-reports/. *These files are often CRUCIAL to diagnosing your issue, so please include them.*

https://gist.github.com/Calciume/fcdc704c70436bcc9a5cd1e5a16b1e19

**Additional context**
- Modpack was downloaded with Prism Launcher
- 4 GB of memory allocated (I tried running the modpack on another device with 4 GB allocated and prism launcher and it worked fine)

**Comment by katubug** [comment]
Hello, thanks for reporting! Unfortunately this is a hardware issue, and I
have never used a Mac so I cannot offer any real help.

The error log you sent suggests that it's an issue with your Java
installation, but googling the error doesn't give me anything I understand
well enough to pass along.

The relevant line is

"#  SIGBUS (0xa) at pc=0x0000000111a294e4, pid=95258, tid=68879"

if you want to try googling it yourself. Otherwise, I would ask a
Mac/Minecraft related forum on Reddit or something.

Sorry!
