### ISSUE TITLE
[Crash]: Chunks Messed Up?

### ISSUE THREAD

**Issue by ochimmo** [katubug/CottageWitch119#63]
### Modpack Version Used

 1.15.16

### What happened?

I start the game and load into it but crash after 20-40 min of playing. I see a chunk that don't load in with textures and is messed up and then i crash. It happens fast enough so i can't screenshot it. It happens at random chunks but it might be a structure with textures that  lag out or won't load??

### Relevant latest.log

```shell
https://gist.github.com/ochimmo/5a74de3a8b3d5961575a08eb4f45c2c9
```

### Relevant crash report

```shell
https://gist.github.com/ochimmo/87f54a56e656cef0e33fbe13af588d6b

https://gist.github.com/ochimmo/c11d79da8da55d69b0f3ea05093fd366
```

**Comment by katubug** [comment]
Okay! So I have good news and bad news. The good news is, your game is
perfectly normal and everything SHOULD be running smoothly. The bad news
is, there's a hardware issue that is causing you to run out of memory while
exploring, which is why your game crashes.

Firstly, I'd check to make sure you have 6-8gb of RAM allocated to the pack.

Next, the hardware error says "EXCEPTION_ACCESS_VIOLATION (0xc0000005) at
pc=0x000001c31857fddb, pid=16328, tid=14680" - I'm not sure what this
means, and google isn't helping me. But you can ask over at the Modded MC
discord - https://discord.com/invite/moddedmc and they might be able to
help.

My guesses to fix it would be to a) update your version of Java to the
latest Java 17, or b) run Curseforge in Admin Mode.

I hope this helps!
