### ISSUE TITLE
Handcrafted boards can't be crafted using stonecutter

### ISSUE THREAD

**Issue by ghostflower67** [katubug/CottageWitch119#64]
### Modpack Version Used

1.19.2

### What happened?

I've been trying to make boards from the handcrafted mod and its not working/ letting me craft the boards no matter what i try. I tried to delete handcrafted then redownload a newer version and then it wont let me play

**Comment by katubug** [comment]
Hi! Firstly, just so you know, it's not a good idea to update mods within a
modpack, because it can break things! You should only update the modpack
itself. You said you're on version 1.19.2 of the modpack, but that's
actually your Minecraft version. The modpack version is something different
- I'll assume you're on 1.15.16.

The issue with the Handcrafted boards is that the Spelunkery mod makes the
Stonecutter not compatible with the Handcrafted mod. For right now, you'll
need to make them with the Saws from Create. We'll look into adding new
recipes for the next update, though!

Thanks for reporting!

**Comment by wiredwhiskers** [comment]
Additional Recipe Provided, as well as coming Hexerei woodcutter recipes for Handcrafted Boards
