### ISSUE TITLE
Not able to sprint in multiplayer

### ISSUE THREAD

**Issue by pxytxn** [katubug/CottageWitch119#66]
### Modpack Version Used

1.16.2

### What happened?

I have reset my server, my game, changed keybinds, and even un/reinstalled the modpack, but for some reason, I am unable to run in multiplayer! Any clue is this is tied to a mod or something? (PS. No, i am not hungry T-T) Plz Help!

**Comment by katubug** [comment]
This is the first time I've heard of this! I'm not sure what could be
causing it. Is your shift key working? To my knowledge there's no mod which
affects running in this way.

We might have a mod which prevents the FoV from changing? So maybe you're
running but it's less obvious because there FoV isn't changing.

Those are the only things I can think of.

**Comment by sigmastar00** [comment]
Some versions of the modpack had the FOV change on sprinting disabled, which caused many people to think that sprinting wasn't working. You can re-enable the FOV change from the accessibility menu. If it turns out that wasn't the problem, feel free to open another issue!
