### ISSUE TITLE
[Crash]: Game crashes when opening up loot chests

### ISSUE THREAD

**Issue by Slvrb33tl3** [katubug/CottageWitch119#68]
### Modpack Version Used

1.16.2hotfix Client 1.16 Server Pack

### What happened?

Opening any loot chests on server is crashing game. I have the CottageWitch-ServerPack-1.16 installed but removed the Better Fishing Rods and OPAC mods that you said you removed from the client because they are not removed from the server pack. Any time I have tried to open a loot chest the game immediately crashes.

**Comment by katubug** [comment]
It's not safe to use the 1.16 serverpack with 1.16.2 regardless of adding
or removing mods, because of other changes to the pack. You'll need to
downgrade clients to 1.16, or upload the full 1.16.2hotfix pack (removing
all client side mods). The second option is only recommended if you're
pretty tech savvy.

I'm sorry for the trouble - curseforge has been yanking us around for weeks
now and their support is less than stellar. Hopefully we'll get it
addressed soon!
