### ISSUE TITLE
Can't find avocados?

### ISSUE THREAD

**Issue by ghostflower67** [katubug/CottageWitch119#89]
I can't seem to find any avocados or any avocado trees in my world and I really don't want to make a new world since I have so much progress on my current world. I don't know if it's a bug or something but when I search them up in the search bar thing they show up I just can't seem to find them at all, and I've searched high and low for them.

**Comment by katubug** [comment]
I don't have much advice to offer - they are obtainable, and I haven't changed their spawn rate or anything. In a future update, we will be adding in the Market from Farming For Blockheads, which will let you buy the seeds. In the meantime, you could add the mod manually, but you'll need to find out how to configure it yourself if you don't want to wait. Otherwise, try asking the mod author if there's another way to obtain them. :)
